# Welcome to Jupyter Notebook

In [1]:
# https://medium.datadriveninvestor.com/how-can-i-customize-jupyter-notebook-into-dark-mode-7985ce780f38

In [2]:
import numpy as np


In [3]:
myarray = np.array([1,2,4,5], np.int8)

In [4]:
myarray[3]

5

In [5]:
myarray_2d = np.array([[2,5,6,78,50]], np.int16)

In [6]:
myarray_2d

array([[ 2,  5,  6, 78, 50]], dtype=int16)

In [7]:
myarray_2d[0,1]

5

In [8]:
myarray_2d.shape #to know the shape (row,col)

(1, 5)

In [9]:
myarray_2d.dtype #to know the datatype

dtype('int16')

**Array Creation: Conversation from other python structures**

In [10]:
listarray = np.array([[1,2,4], [6,7,8], [10,11,12]])

In [11]:
listarray

array([[ 1,  2,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [12]:
listarray.size

9

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
#dtype = object
np.array({3,45,59})

array({3, 59, 45}, dtype=object)

In [16]:
zeros = np.zeros((2,5)) #(row,col)

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# create a array using range
range_array = np.arange(10)

In [19]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# same linespace array
line_space_array = np.linspace(1,10,5) #(start, dest, no. of element with same space)

In [21]:
line_space_array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
# empty array with random value. We can change the value by assigning
emp = np.empty((4,6)) #(row,col)

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33512173e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.37962185e-306,
        1.37962049e-306, 1.24610723e-306, 1.42410974e-306]])

In [24]:
emp[0,0] = 3

In [25]:
emp

array([[3.00000000e+000, 4.67296746e-307, 1.69121096e-306,
        1.33512173e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.37962185e-306,
        1.37962049e-306, 1.24610723e-306, 1.42410974e-306]])

In [26]:
#copy an array to create a same size array
emp_like = np.empty_like(line_space_array)

In [27]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
emp_like[0] = 5 # changing by assignment operator

In [29]:
emp_like

array([ 5.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [30]:
#identity matrics
ide_array = np.identity(10) #10x10 matrix

In [31]:
ide_array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
ide_array.shape

(10, 10)

In [33]:
# how to reshape any array
arr_reshape = np.arange(99)

In [34]:
arr_reshape.reshape(3,33) # this is used to reshape any array.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr_reshape = arr_reshape.ravel()

In [36]:
arr_reshape.shape

(99,)

In [37]:
arr_reshape # to back again previous size

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
twod_array = [[1,2,3],[4,5,6],[7,8,9]]

In [39]:
twod_array = np.array(twod_array)

In [40]:
twod_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
twod_array.sum(axis=0) # axis=0 means it will calculate col wise.

array([12, 15, 18])

In [42]:
twod_array.sum(axis=1) #axis=0 means it will calcualte row wise.

array([ 6, 15, 24])

In [43]:
twod_array.T # to transpose matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
twod_array.flat # it creates an iterator

In [45]:
for i in twod_array.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [46]:
twod_array.ndim #dimension

2

In [47]:
one = np.array([1,4,10,8,9])

In [48]:
one.argmax() # return index where maximum element is there

2

In [49]:
one.argmin() # return index where minimum element is there

0

In [50]:
one.argsort()

array([0, 1, 3, 4, 2], dtype=int64)

In [51]:
#dealing with 2d array
twod_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
twod_array.argmax() # this will return index after arranging all the elements as a 1d array

8

In [53]:
twod_array.argmin()

0

In [54]:
twod_array.argmax(axis = 0) # this will return maximum element among the col wise (axis = 0)

array([2, 2, 2], dtype=int64)

In [55]:
twod_array.argmin(axis = 1) # this will return maximum element among the col wise (axis = 0)

array([0, 0, 0], dtype=int64)

In [56]:
twod_array.argsort(axis=0) 

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [57]:
another = [[15,2,1],[7,17,9],[5,7,12]]

In [58]:
another = np.array(another)

In [59]:
another

array([[15,  2,  1],
       [ 7, 17,  9],
       [ 5,  7, 12]])

In [60]:
another.argmax(axis=0)

array([0, 1, 2], dtype=int64)

In [61]:
another.argmin(axis=0)

array([2, 0, 0], dtype=int64)

In [62]:
another.argsort(axis=0)

array([[2, 0, 0],
       [1, 2, 1],
       [0, 1, 2]], dtype=int64)

In [63]:
another.argmin(axis=1)

array([2, 0, 0], dtype=int64)

In [64]:
another.argmax(axis=1)

array([0, 1, 2], dtype=int64)

In [65]:
another.argsort(axis=1)

array([[2, 1, 0],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [66]:
another1 = np.array([[15,  2,  1],
       [ 7, 17,  9],
       [ 5,  7, 12]])

In [67]:
another1

array([[15,  2,  1],
       [ 7, 17,  9],
       [ 5,  7, 12]])

In [68]:
another+another1

array([[30,  4,  2],
       [14, 34, 18],
       [10, 14, 24]])

In [69]:
another*another1

array([[225,   4,   1],
       [ 49, 289,  81],
       [ 25,  49, 144]])

In [71]:
np.sqrt(another) # squre root of each element in matrix(array)

array([[3.87298335, 1.41421356, 1.        ],
       [2.64575131, 4.12310563, 3.        ],
       [2.23606798, 2.64575131, 3.46410162]])

In [72]:
np.where(another>10) # it will return a tuple axis wise. first axis 0 and then axis 1

(array([0, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [73]:
myarray

array([1, 2, 4, 5], dtype=int8)

In [74]:
np.where(myarray>3) # there has only one axis that's why it has printed only one tuple element

(array([2, 3], dtype=int64),)

In [75]:
np.count_nonzero(another)

9

In [77]:
np.nonzero(another) # check the 1st line and 2nd line correspondingly

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [79]:
another

array([[15,  2,  1],
       [ 7, 17,  9],
       [ 5,  7, 12]])

In [80]:
another[0,1] = 0

In [81]:
np.nonzero(another) #[0,1] has been removed

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [82]:
import sys

In [83]:
py_ar = [2,4,5,6]

In [84]:
num_ar = np.array(py_ar)

In [85]:
sys.getsizeof(1)*len(py_ar) # to define the size of python array

112

In [86]:
num_ar.itemsize*num_ar.size # to define the size of numpy array

16

In [88]:
num_ar.tolist() # to convert numpy array into python list

[2, 4, 5, 6]